<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../KillMutants.Core/KillMutants.Core.csproj" />
    <ProjectReference Include="../KillMutants.Platform/KillMutants.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KillMutants.Core.Tests" />
    <InternalsVisibleTo Include="KillMutants.EndToEnd.Tests" />
  </ItemGroup>

</Project>
